Fix #1281, remove testrunner and convert testcase to app
nasa/cFE pull request #1292
Opened 2021-04-09 19:15 UTC by jphickey

**Describe the contribution**
- Removes the separate CFE "testrunner" module and moves the logic associated with running a test into cfe_assert library.
- Converts the "testcase" module from a library into an app, by calling into the runner logic that is now inside cfe_assert.

This permits tests to be invoked at any time by issuing the ES "start app" command and specifying the testcase app.

**Testing performed**
Build and sanity check CFE.
Run all currently-implemented functional tests

**Expected behavior changes**
Each functional test is a separate app, not a library, so it can be started and stopped via ES command like any other app.

**System(s) tested on**
Ubuntu 20.04

**Additional context**
Requires #1276 as prerequisite

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

2021-04-12 19:19 UTC, jphickey commented
Rebased to latest mainline.

2021-04-13 20:01 UTC, zanzaben requested changes
Need to also update cFS/cfe/docs/README_functionaltest.md file with the new instructions on how to run the tests.

2021-04-14 17:28 UTC, jphickey commented
> Need to also update cFS/cfe/docs/README_functionaltest.md file with the new instructions on how to run the tests.

Updated in ec2d2f679

2021-04-14 17:44 UTC, skliper commented
CCB:2021-04-14 - APPROVED

2021-04-14 17:48 UTC, zanzaben approved these changes

2021-04-15 14:33 UTC, zanzaben requested changes
2 of the test are failing and need to be updated. 

Test App Info -> EntryPt (line 66)
Test App Info -> FileName (line 69)

2021-04-20 14:57 UTC, jphickey commented
Update to correct name checks.  See commit e4afd35

2021-04-20 14:59 UTC, jphickey commented
Corrected string checks in commit 23c835b

2021-04-20 15:15 UTC, zanzaben approved these changes

2021-04-22 15:20 UTC, merged