Fix #1298, add Current Time Functional Test
nasa/cFE pull request #1415
Opened 2021-04-22 18:38 UTC by zanzaben

**Describe the contribution**
Fixes #1298
adds new functional tests for Time Current API.

**System(s) tested on**
Ubuntu 20.04

**Additional context**
This is a just testing the nominal cases. More in depth tests will have to be added later.

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2021-04-28 16:11 UTC, astrogeco commented
[CCB:2021-04-27](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-April-28-2021) APPROVED with changes
- Race condition with the equality comparision?
- Shouldn't all of these test have a "slop factor" of sorts 
- Use osal function to get difference between two times and check the difference in the nano or subseconds

2021-04-28 16:11 UTC, astrogeco requested changes
See ccb comment

2021-05-03 16:11 UTC, zanzaben commented
Fixed issue of slop factor.

2021-05-04 00:15 UTC, astrogeco commented
@zanzaben looks like the conflicts you mentioned are here!

2021-05-04 16:20 UTC, merged