Fix #814, add ES Misc Functional test
nasa/cFE pull request #1586
Opened 2021-05-27 19:06 UTC by zanzaben

**Describe the contribution**
Fixes #814
Test for the api calls in Misc section. 

**Testing performed**
Build and run unit test

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2021-06-02 16:06 UTC, astrogeco requested changes
CCB:2021-06-02, Change INT32_EQ to UINT32

2021-06-02 16:11 UTC, astrogeco commented
[CCB:2021-06-02](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-02-2021) APPROVED with Changes
- Conversation about logs and testing using external script with CI and TO versus using a test app
- Add some more tests with a vararg

2021-06-03 12:20 UTC, skliper approved these changes

2021-06-03 12:21 UTC, skliper commented
Looks good, although that last merge commit message doesn't comply with our preferred style :)

2021-06-03 13:49 UTC, zanzaben commented
> Looks good, although that last merge commit message doesn't comply with our preferred style :)

Do we want "Fix #814, Fix CCB comments" instead?

2021-06-03 15:19 UTC, skliper commented
Take a look at https://chris.beams.io/posts/git-commit/.  "Fix #814, Fix CCB comments" does not sufficiently describe what's in the commit.

2021-06-15 15:24 UTC, merged