Fix #567, Document CFE_ES_RunLoop increment task counter behavior
nasa/cFE pull request #1601
Opened 2021-06-03 17:20 UTC by skliper

**Describe the contribution**
Fix #567 - updated documentation

**Testing performed**
CI - documentation only

**Expected behavior changes**
None

**System(s) tested on**
CI

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

2021-06-03 17:59 UTC, jphickey approved these changes

2021-06-04 13:54 UTC, zanzaben commented
The App Developer's Guide should also be updated.

2021-06-04 14:22 UTC, zanzaben requested changes
The App Developer's Guide should also be updated.

2021-06-07 16:02 UTC, skliper commented
> The App Developer's Guide should also be updated.

Where specifically?

2021-06-07 16:10 UTC, skliper commented
> The App Developer's Guide should also be updated.

The developer's guide has CFE_ES_RunLoop in the sample code and the API documents use.  No further updates identified.  Should be sufficient for closing current issue.  Open a new issue (or provide explicit requested changes here) for additional changes.

2021-06-07 16:14 UTC, zanzaben approved these changes

2021-06-09 16:11 UTC, astrogeco commented
[CCB:2021-06-09](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-09-2021) APPROVED

2021-06-10 21:29 UTC, merged