Fix #1667, CFE_SB_MsgHdrSize returns size_t but still attempts to ret…
nasa/cFE pull request #1674
Opened 2021-07-19 16:28 UTC by oliverhamburger

…urn CFE status code

**Describe the contribution**
Fixes Issue #1667 by changing the return type in CFE_SB_MsgHdrSize and CFE_SB_GetUserDataLength

**Testing performed**
Build and ran unit tests

**Expected behavior changes**
CFE_SB_MsgHdrSize and CFE_SB_GetUserDataLength now return 0 when *MsgPtr is NULL

**System(s) tested on**
 Ubuntu 20.04

**Additional context**
Add any other context about the contribution here.

**Contributor Info**
Oliver Hamburger GSFC

2021-07-19 19:15 UTC, zanzaben approved these changes

2021-07-19 21:19 UTC, jphickey requested changes
Just a minor recommendation - when documenting return values, the `\returns` tag should be just a generic description, and the `\retval` tag should be used for documenting specific values.

So, I'd recommend something like:

     \returns Estimated number of bytes in the message header for the given message
     \retval 0 if an error occurs, such as if the MsgPtr argument is not valid or header type cannot be identified

(Also to be pedantic, it is `MsgPtr` that is checked for NULL, not `*MsgPtr`)

2021-07-20 16:51 UTC, jphickey approved these changes
Looks good.  I would only recommend a "squash commit" now to consolidate the 3 commits into one on this branch.  But otherwise looks good.

2021-07-20 23:13 UTC, merged

2022-10-21 14:33 UTC, dmknutsen commented
@oliverhamburger can you fill out a CLA?  We are trying to submit an NTR for the Draco development cycle.
https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md

2022-10-21 16:14 UTC, oliverhamburger commented
> @oliverhamburger can you fill out a CLA? We are trying to submit an NTR for the Draco development cycle. https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md

CLA sent to GSFC-SoftwareRelease@mail.nasa.gov