Fix #1645, Add resource ID API functional tests
nasa/cFE pull request #1716
Opened 2021-07-27 19:24 UTC by nmullane

**Describe the contribution**
- Fixes #1645
- Adds functional tests for each of the following functions
  - CFE_ES_AppID_ToIndex
  - CFE_ES_LibID_ToIndex
  - CFE_ES_TaskID_ToIndex
  - CFE_ES_CounterID_ToIndex

**Testing performed**
Steps taken to test the contribution:
1. Build CFE and run all functional tests

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - no impact to behavior

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Niall Mullane - GSFC 582 Intern

2021-08-09 14:52 UTC, zanzaben approved these changes

2021-08-09 15:44 UTC, skliper requested changes
Also test for range, should be within maximum allowed.  Comment comes from a previous similar test, which I think is still valid here.

2021-08-09 16:37 UTC, nmullane commented
> Also test for range, should be within maximum allowed. Comment comes from a previous similar test, which I think is still valid here.

There is an issue for this with an associated branch on my fork that does this, but Gerardo suggested I create a second PR for that once this is merged.
https://github.com/nasa/cFE/issues/1760

2021-08-09 17:35 UTC, skliper approved these changes

2021-08-09 21:16 UTC, merged

2021-08-11 16:40 UTC, astrogeco commented
[CCB:2021-08-11](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-11-2021) APPROVED
- Add call for background wakeup