Fix #1725 Update time_UT.c to use UtAssert_MIR
nasa/cFE pull request #1732
Opened 2021-07-29 18:24 UTC by pepepr08

**Describe the contribution**
Fixes #1725 Updated time_UT.c to start using the new UtAssert_MIR to avoid incorrect use of UtAssertEx.

This update requires https://github.com/nasa/osal/pull/1122 to be merged first.

**Testing performed**
Steps taken to test the contribution:
1. Pulled OSAL repo with the UtAssert_MIR changes
2. Rebuild cFS
3. Run unit tests.... All passed.
4. Set a custom epoch time
5. rebuild and run unit tests... All passed.
6. Manually run ./coverage-time-ALL-testrunner and verify expect output:

`[  MIR] 06.004 time_UT.c:902 - Confirm adding seconds = 4294967295, subseconds = 4294967295 to configured EPOCH results in time 0214-039-06:28:15.99999`

**Expected behavior changes**
No expected changes in behavior. 

**System(s) tested on**
Ubuntu 18.04 VM

**Contributor Info - All information REQUIRED for consideration of pull request**
Jose F. Martinez Pedraza / NASA GSFC

2021-07-29 18:33 UTC, skliper approved these changes

2021-07-29 19:07 UTC, zanzaben commented
Can you also update the assert in es_mic_test.c to the new macro.

2021-07-29 19:07 UTC, zanzaben requested changes
Can you also update the assert in es_mic_test.c to the new macro.

2021-07-30 13:27 UTC, zanzaben approved these changes

2021-08-04 16:06 UTC, astrogeco commented
[CCB:2021-08-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-04-2021) APPROVED

2021-08-04 22:39 UTC, merged