Fix #1649, Add Functional Test for EVS Reset Filters API.
nasa/cFE pull request #1749
Opened 2021-08-02 15:40 UTC by zanzaben

**Describe the contribution**
Fixes #1649
Add Functional Test for EVS Reset Filters APIs.

**Testing performed**
Build and run unit test

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2021-08-04 14:17 UTC, skliper requested changes

2021-08-04 14:17 UTC, skliper commented on modules/cfe_testcase/src/evs_filters_test.c
> +    UtAssert_INT32_EQ(CFE_EVS_ResetFilter(1), CFE_SUCCESS);
Suggest a comment here, something like - `Test logic below depends on the test case registering an EID of 1 and not registering 0, and the resets in theory could impact test behavior/management related to events.  Although the expectation is either all or none of an EID would be filtered (no use case for a "counting" filter within the test app) so for nominally this is no impact.`  Provides clues for maintenance.

2021-08-04 16:20 UTC, astrogeco commented
[CCB:2021-08-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-04-2021) APPROVED

2021-08-10 13:41 UTC, astrogeco commented
@zanzaben can you fix the conflicts?

2021-08-10 13:51 UTC, zanzaben commented
> @zanzaben can you fix the conflicts?

conflicts resolved.

2021-08-10 14:01 UTC, astrogeco commented
Cool, how about @skliper's comment?

2021-08-10 14:41 UTC, skliper approved these changes

2021-08-10 14:59 UTC, astrogeco commented
Resolved one more conflict and merged manually. Workflows run successfully, see https://github.com/astrogeco/cFE/runs/3292238330

2021-08-10 15:00 UTC, merged