Fix #1644, finish ES misc API functional test
nasa/cFE pull request #1766
Opened 2021-08-05 15:03 UTC by nmullane

**Describe the contribution**
Fixes #1644 

**Testing performed**
1. Build and run cfe functional tests

**Expected behavior changes**
- No impact to behavior

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Niall Mullane - GSFC 582 Intern

2021-08-05 17:37 UTC, skliper requested changes

2021-08-05 17:37 UTC, skliper commented on modules/cfe_testcase/src/es_misc_test.c
> +    CFE_ES_ProcessAsyncEvent();
Wrap in UtAssert_VOIDCALL (depends on nasa/osal#1125) so it gets reported in the log.

2021-08-05 17:41 UTC, skliper approved these changes

2021-08-05 17:45 UTC, nmullane commented
I'll work on this.

2021-08-05 17:47 UTC, nmullane commented
This PR depends on https://github.com/nasa/osal/pull/1125

2021-08-09 13:53 UTC, nmullane commented
I believe this should be passing now. Is there a way to rerun the github actions checks?

2021-08-09 14:18 UTC, skliper commented
Reran and all passed.

2021-08-09 14:47 UTC, zanzaben approved these changes

2021-08-09 21:31 UTC, merged