Fix #1691, Add External Time Source Functional Tests
nasa/cFE pull request #1783
Opened 2021-08-10 16:34 UTC by zanzaben

**Describe the contribution**
Fixes #1691
Add External Time Source Functional Tests

**Testing performed**
Build and run unit test

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2021-08-11 14:40 UTC, skliper requested changes

2021-08-11 14:40 UTC, skliper commented on modules/cfe_testcase/src/time_external_test.c
> +
How about adding a 2 sec delay and check the CallbackFunction is called at least once?  Could use the FT count global...  Not a big deal but would be an easy functional check.

2021-08-11 14:40 UTC, skliper commented on modules/cfe_testcase/src/time_external_test.c
> +
Worth a UtPrintf or comment here that the following time calls could impact the system timekeeping.  Likely impact is incorrect time for one update cycle, a rejected external time update, multiple tone's or external updates detected, or similar.  The call here confirms the implementation is properly included, more extensive timekeeping verification is a project/system responsibility.

2021-08-11 16:13 UTC, astrogeco commented
[CCB:2021-08-11](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-11-2021) Needs more work

2021-08-12 15:14 UTC, zanzaben commented
This current implementation of verifying the callback function is not 100% reliable yet.

2021-08-12 18:55 UTC, skliper requested changes
Embedded...

2021-08-12 18:55 UTC, skliper commented on modules/cfe_testcase/src/time_external_test.c
> +    OS_TaskDelay(2000);
How about 2500 to give a little margin?

2021-08-12 18:55 UTC, skliper commented on modules/cfe_testcase/src/time_external_test.c
> +    OS_TaskDelay(2000);
same 2500

2021-08-12 18:55 UTC, skliper commented on modules/cfe_testcase/src/time_external_test.c
> +        UtAssert_MIR("Timing performance of this system is insufficient to test CFE_TIME_RegisterSynchCallback");
How about "...likely insufficient..."  Comment might help also, something about the callback only gets called if the elapsed time between tones is within the configured tolerance.  Manual inspection is required to determine if there is an actual failure in registering or executing the callback or if it's a timing issue within the system under test, so the test is not automatically failed here but requires further analysis.

2021-08-16 19:09 UTC, skliper approved these changes

2021-08-16 19:22 UTC, merged