Fix #1760, check resource ID idx is less than max
nasa/cFE pull request #1804
Opened 2021-08-11 16:05 UTC by nmullane

**Describe the contribution**
Fixes #1760 

**Testing performed**
Steps taken to test the contribution:
1. Build and run cfe functional tests

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Niall Mullane - GSFC 582 Intern

2021-08-11 16:42 UTC, astrogeco commented
[CCB:2021-08-11](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-11-2021) APPROVED with CHANGES
- Add call to "unregister"

2021-08-11 18:14 UTC, astrogeco commented
[CCB:2021-08-11](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-11-2021) APPROVED

2021-08-11 20:39 UTC, skliper requested changes
Just adding the request to change so it doesn't get lost.

2021-08-11 20:39 UTC, skliper commented on modules/cfe_testcase/src/es_resource_id_test.c
>      UtAssert_UINT32_EQ(CFE_ES_RegisterGenCounter(&CounterId, CounterName), CFE_SUCCESS);
Unregister counter at end of test

2021-08-12 17:52 UTC, nmullane commented on modules/cfe_testcase/src/es_resource_id_test.c
>      UtAssert_UINT32_EQ(CFE_ES_RegisterGenCounter(&CounterId, CounterName), CFE_SUCCESS);
done 👍

2021-08-12 18:59 UTC, skliper approved these changes

2021-08-13 18:47 UTC, merged