Fix #1858, remove unused CFE_TBL_ERR_FILE_NOT_FOUND
nasa/cFE pull request #1859
Opened 2021-08-20 13:24 UTC by jphickey

**Describe the contribution**
Status code no longer produced by current implementation, it returns CFE_TBL_ERR_ACCESS when unable to open a file.

Fixes #1858

**Testing performed**
Build and sanity check CFE, run all tests

**Expected behavior changes**
None

**System(s) tested on**
Ubuntu

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

2021-08-20 13:44 UTC, skliper approved these changes

2021-08-20 16:40 UTC, zanzaben requested changes
Should remove it from here as well 
https://github.com/nasa/cFE/blob/a0c2de62934e61a93bb4282c0fc784cf4be50da9/modules/cfe_testcase/src/tbl_content_mang_test.c#L56

2021-08-20 22:42 UTC, astrogeco commented
> Should remove it from here as well
> 
> https://github.com/nasa/cFE/blob/a0c2de62934e61a93bb4282c0fc784cf4be50da9/modules/cfe_testcase/src/tbl_content_mang_test.c#L56

2021-08-20 22:54 UTC, merged

2021-08-25 16:24 UTC, astrogeco commented
[CCB:2021-08-25](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-25-2021) APPROVED