Fix #1895, Improve TIME branch coverage
nasa/cFE pull request #1896
Opened 2021-08-26 16:42 UTC by skliper

**Describe the contribution**
Fix #1895, TIME now at 99.8%/99.7% with just #1841 outstanding

**Testing performed**
Build/run/verify coverage for unit tests

**Expected behavior changes**
None

**System(s) tested on**
 - Hardware: Intel i5/Docker
 - OS: Ubuntu 18.04
 - Versions: Bundle main + this commit

**Additional context**
Remaining uncovered: 2 lines, 1 branch:
 - #1841

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

2021-08-30 21:02 UTC, pepepr08 requested changes

2021-08-30 21:02 UTC, pepepr08 commented on modules/time/ut-coverage/time_UT.c
> +    /* CFE_ES_AppID_ToIndex failure */
Duplicated comment

2021-08-30 22:29 UTC, skliper commented on modules/time/ut-coverage/time_UT.c
> +    /* CFE_ES_AppID_ToIndex failure */
Resolved in 4941284

2021-08-30 22:30 UTC, pepepr08 approved these changes

2021-08-31 13:43 UTC, merged

2021-09-01 16:09 UTC, astrogeco commented
[CCB:2021-09-01](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-01-2021) APPROVED