Fix #1907, Cmake modifiable table tool path parameter
nasa/cFE pull request #1910
Opened 2021-08-30 09:00 UTC by pavll

Cmake option to change the path of the ef2cfetbl executable file via the TABLETOOL_EXE environment variable. This also enables the user to specify other tools as table tool if needed.

**Describe the contribution**
- Fixes #1907 

**Testing performed**
1. Github actions

**Expected behavior changes**
- Nothing only if TABLETOOL_EXE environment variable is set. Then the cmake would use the content as path to an executable used for transforming lib into tbl.

**Additional context**
See above.

**Contributor Info - All information REQUIRED for consideration of pull request**
@pavll

2021-08-31 19:57 UTC, astrogeco commented
Hey @pavll thanks for the contribution, we're still debating what approach we want to take with this but in the meantime one small improvement would be to use CMake cache variables instead of environment ones.

2021-08-31 20:13 UTC, pavll commented
Ok, thanks for the quick info + tip.

2021-08-31 20:51 UTC, pavll commented
Ok, now you can run your Mission Build with `-DTABLETOOL_EXECUTABLE=/path/to/my/custom/tabletool`, and then it will set it as **CMake cache variable** which then will be used in Arch Build to parse it (if set, else the default) thought `-DTBLTOOL` to the Generate Table (_like it is at the moment_).

2022-10-11 13:12 UTC, dzbaker commented
@jphickey Would you be able to review this PR?

2022-10-21 14:08 UTC, jphickey requested changes
I'm not seeing how the value gets passed from the top-level mission build into the arch build where it is used.

BUT - I'm not entirely convinced that this is the right way to go in the first place.  Ideally, the intent with the issue #1907 was to make the table build method more modular. With this change, only the path to the EXE file for the tool can be modified, but all other parts of the build process are kept the same.  This means that whatever alternate tool is provided, must have exactly the same functionality as `elf2cfetbl`, including all its quirks.  So at that point I don't know why someone would need to override it, it has to do what it is expected to do at that particular step.

I'd rather see a change that only captures the table build metadata here (include paths, compile defs, source files, etc) and defers the actual binary generation to a user-defined script that runs at the mission level.  This way, a user can control the whole process, and actually do something different (as opposed to parsing an ELF file which has always been troublesome/problematic).

2022-10-21 14:12 UTC, jphickey commented
Also - as this has been stale for over a year now, I haven't heard users clamoring for something like this - if it is not a pressing issue I wouldn't risk possible unintended side effects by adding a feature that isn't high priority or unlikely to be used.  

In many ways there are already too many options/special features/overrides in the build as it is, and many aren't tested on a regular basis so might be broken.

2022-10-26 11:53 UTC, dzbaker commented
It may be best to simply close this one for now. @paulober @jphickey, would you agree?

2022-10-26 13:10 UTC, jphickey commented
> It may be best to simply close this one for now. @paulober @jphickey, would you agree?

Yes, I would agree.  

Recommendation for a user that needs something different would be to copy the "add_cfe_tables" function in its entirety into your `arch_build_custom.cmake` file and then modify it to do what you want.

2022-10-26 14:02 UTC, paulober commented
> It may be best to simply close this one for now. @paulober @jphickey, would you agree?

I agree with that too. The overwrite option via `arch_build_custom.cmake` sounds much clearer and easier.

2022-10-26 14:02 UTC, closed without merging