Fix #1906, Enforce minimum code coverage
nasa/cFE pull request #1938
Opened 2021-09-07 18:34 UTC by skliper

**Describe the contribution**
Added enforcement of minimum coverage to CI, currently set to numbers achieved once all coverage PR's are in (ES and SB pending)

**Testing performed**
See results on branch with ES/SB merges at: https://github.com/skliper/cFE/runs/3536944299?check_suite_focus=true (PASSED)

**Expected behavior changes**
Only impact is to fail the workflow if code is added without associated code coverage.

**System(s) tested on**
CI (also ran it locally for testing)

**Additional context**
The numbers can be adjusted if code is added that really can't be covered (although we should avoid this) and/or as we resolve open coverage issues (all are documented).

Needs #1936 and #1922 merged to pass.

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

2021-09-07 20:06 UTC, pepepr08 requested changes

2021-09-07 20:06 UTC, pepepr08 commented on .github/workflows/code-coverage.yml
> +          if [ $(($branch_diff > $missed_branches)) == 1 ] || [ $(($line_diff > $missed_lines)) == 1 ]
would something like this work?
```
if [ $branch_diff -gt $missed_branches ] || [ $line_diff -gt $missed_lines ]
```

2021-09-07 21:43 UTC, pepepr08 approved these changes

2021-09-07 21:55 UTC, merged

2021-09-08 16:03 UTC, astrogeco commented
[CCB:2021-09-08](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-08-2021) APPROVED