Fix #1957, Functional CRC converted to MIR to handle different implementations
nasa/cFE pull request #1958
Opened 2021-09-16 19:17 UTC by skliper

**Describe the contribution**
- Fix #1957 
Simplified and made confirmation of results MIR

**Testing performed**
MCP750 (and CI)

**Expected behavior changes**
Functional CRC tests no longer fail vs hard coded values

**System(s) tested on**
 - Hardware: MCP750
 - OS: VxWorks 6.9
 - Versions: Bundle main + #1956 + #1953 + this commit

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

2021-09-21 14:47 UTC, zanzaben requested changes

2021-09-21 14:50 UTC, skliper commented on modules/cfe_testcase/src/es_misc_test.c
> +    UtAssert_VOIDCALL(Result = CFE_ES_CalculateCRC(Data, sizeof(Data), 0, CFE_MISSION_ES_CRC_8));
0 actually could be a real checksum, so we shouldn't assume it's not implemented.

2021-09-21 14:51 UTC, skliper commented on modules/cfe_testcase/src/es_misc_test.c
> +    UtAssert_MIR("Confirm CRC32 of \"%s\" is %lu", Data, (unsigned long)Result);
Same, user needs to confirm based on implementation (0 may or may not be correct).  Maybe they thought they had it implemented but didn't...

2021-09-21 15:00 UTC, merged

2021-09-22 16:29 UTC, astrogeco commented
[CCB:2021-09-21](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-22-2021) APPROVED