Fix #2228, Update UTs to use correct cmd types
nasa/cFE pull request #2229
Opened 2022-12-07 19:56 UTC by dmknutsen

Fix #2228, Update UTs to use correct cmd types

**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
These are the unit test updates requested by @shion-ito-nasa, and are associated with #2228 
The requested change originated from #2220

**Testing performed**
Build and run all tests'

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 22.04 and 20.04 (workflows)

**Contributor Info - All information REQUIRED for consideration of pull request**
Dan Knutsen
NASA/Goddard

2022-12-08 15:01 UTC, jphickey requested changes
If you want, I could theoretically take this one and do the updates I suggested.  The problem is the change as proposed will break the EDS build.  (Fundamental issue is that we don't actually define a real message called `NoArgsCmd` in any of these modules; that was just an implementation shortcut to avoid repeating the same definition, so it really shouldn't be referenced outside of the msg.h file).

2022-12-08 17:29 UTC, shion-ito-nasa commented on modules/tbl/ut-coverage/tbl_UT.c
> +        CFE_TBL_NoArgsCmd_t NoArgsCmd;
This is a understandable change. I went ahead and replaced it with CFE_TBL_NoopCmd_t and tested it on our unit test and it has worked.

2022-12-08 17:29 UTC, shion-ito-nasa commented on modules/es/ut-coverage/es_UT.c
> +        CFE_ES_NoArgsCmd_t           NoArgsCmd;
Same here I tested it and it worked.

2022-12-08 17:31 UTC, shion-ito-nasa commented on modules/evs/ut-coverage/evs_UT.c
> +        CFE_EVS_NoArgsCmd_t           cmd;
Does this change require any support from me?

2022-12-09 18:17 UTC, jphickey commented on modules/es/ut-coverage/es_UT.c
> +        CFE_ES_NoArgsCmd_t           NoArgsCmd;
Fixed in 0f9313d8

2022-12-09 18:18 UTC, jphickey commented on modules/tbl/ut-coverage/tbl_UT.c
> +        CFE_TBL_NoArgsCmd_t NoArgsCmd;
Fixed in 0f9313d8

2022-12-09 18:18 UTC, jphickey commented on modules/evs/ut-coverage/evs_UT.c
> +        CFE_EVS_NoArgsCmd_t           cmd;
Fixed in 0f9313d8

2022-12-20 16:38 UTC, merged