Fix #2297, Create Workflow for IC Bundle Generation
nasa/cFE pull request #2298
Opened 2023-04-19 20:32 UTC by dzbaker

**Checklist (Please check before submitting)**

* [  x ] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).
* [  x ] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
A clear and concise description of what the contribution is.
- Addresses issue #2297.

**Testing performed**
Generated IC branch in fork.

**Expected behavior changes**
Adds new workflow for integration candidate branch generation.

**Contributor Info - All information REQUIRED for consideration of pull request**
Dylan Z. Baker/NASA GSFC 582

2023-04-20 14:41 UTC, jphickey requested changes
Looks OK, but I'd like to discuss the possibility of naming the IC branch using a date-based scheme, e.g.`ic-YYYYMMDD` instead of always calling it `integration-candidate`.  

Once the testing of the IC is done, the branch is simply deleted (this can be because it was merged to main or something broke and we abandon it).

IMO having unique branch names for each IC makes things more manageable.  Is there a reason we need to keep the name the same?

2023-04-20 14:59 UTC, dzbaker commented
> Looks OK, but I'd like to discuss the possibility of naming the IC branch using a date-based scheme, e.g.`ic-YYYYMMDD` instead of always calling it `integration-candidate`.
> 
> Once the testing of the IC is done, the branch is simply deleted (this can be because it was merged to main or something broke and we abandon it).
> 
> IMO having unique branch names for each IC makes things more manageable. Is there a reason we need to keep the name the same?

I think we should consider using the date scheme. The process that I inherited was to use a single integration-candidate branch, so I want to get team concurrence before I change it.

2023-04-20 18:21 UTC, dzbaker commented
CCB 20 April 2023: Configure shell to trigger BASH to exit if something goes wrong in run block. Split run blocks where possible.

2023-04-25 17:43 UTC, jphickey approved these changes

2023-04-25 18:52 UTC, merged