Unloading module after failed app start
nasa/cFE pull request #2616
Opened 2024-12-02 13:27 UTC by tandharia

**Checklist (Please check before submitting)**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).

**Describe the contribution**
Fixes #2615 - Unloading module from memory when an app fails to start

**Testing performed**
Built and ran all tests

**Expected behavior changes**
If an app fails to start because of bad parameters, the module is unloaded from memory and the entry in the OS_module_table removed

**System(s) tested on**
OS: RHEL 8.10

**Contributor Info - All information REQUIRED for consideration of pull request**
Tvisha Andharia - GSFC 582 intern

2024-12-02 14:04 UTC, RichLandau requested changes
The pipeline for commit style is failing, could you please fix your commit message to use the standard form that links the change to the issue?

2024-12-02 14:04 UTC, RichLandau commented on modules/es/fsw/src/cfe_es_apps.c
> +        if (OS_ObjectIdDefined(AppRecPtr->LoadStatus.ModuleId)) {
Please be sure to follow the cFS style with braces on their own line

2024-12-02 14:04 UTC, RichLandau commented on modules/es/fsw/src/cfe_es_apps.c
> +            OS_ModuleUnload(AppRecPtr->LoadStatus.ModuleId);
Please capture the return code and log on error.

2024-12-05 17:58 UTC, RichLandau approved these changes

2024-12-05 19:18 UTC, dzbaker commented
CCB 5 December 2024: Provisionally approved pending squash of commits.

2024-12-10 16:38 UTC, merged